version: '3'

services:
  web:
    build: ./web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./web:/app
    ports:
      - '8000:8000'
  api:
    build: ./api
    volumes:
      - ./api:/app
    ports:
      - '5000:5000'