# Generated by Django 3.0.3 on 2020-04-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rx_core', '0002_patient_crn_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.PositiveSmallIntegerField(choices=[(4, '<55'), (3, '55-64'), (2, '65-75'), (1, '75+')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='alcohol_drinking',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='comorbidity',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=1, verbose_name='Other Health Conditions (Heart Attack, CHD, Stroke)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='disability',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='education_level',
            field=models.PositiveSmallIntegerField(choices=[(1, '<High School'), (1, 'Some High School'), (2, 'High School Grad or GED'), (2, 'Some College'), (3, 'College or More')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='employment_status',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Employed/Self-employed'), (1, 'Not employed'), (4, 'Retired'), (2, 'Not in the workforce')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='general_health_status',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Excellent'), (3, 'Good'), (2, 'Fair'), (1, 'Poor')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='health_insurance',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='height',
            field=models.IntegerField(default=1, verbose_name='Height (m)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='household_income',
            field=models.PositiveSmallIntegerField(choices=[(1, '<$15k'), (2, '$15k-$24.9k'), (3, '$25k-$34.9k'), (4, '$35k-$49.9k'), (5, '$50k or more')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='marital_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Living Alone'), (2, 'Married or Living with SO')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='other_info',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='physical_activity',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='race',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Non-Hispanic White'), (2, 'Non-Hispanic Black'), (1, 'Hispanic'), (4, 'Asian/Pacific Islander'), (3, 'Other')], default=1, verbose_name='Race/Ethnicity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='sex',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Female'), (2, 'Male'), (1, 'Other')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='smoking_activity',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.IntegerField(default=1, verbose_name='Weight (kg)'),
            preserve_default=False,
        ),
    ]
