# Generated by Django 3.0.3 on 2020-04-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rx_core', '0003_auto_20200419_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='crn_score',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='other_info',
            field=models.TextField(default=''),
        ),
    ]
