# Generated by Django 3.0.3 on 2020-04-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rx_core', '0005_patient_arrival_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
