# Generated by Django 3.0.3 on 2020-04-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rx_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='crn_score',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
